apiVersion: v1
kind: Service
metadata:
  name: cloud-native-app-service
spec:
  type: NodePort
  selector:
    app: cloud-native-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
